services:
    mpich:
        image: pikrog/mpich:${MPICH_VERSION}-${BASE_DISTRO_TAG}
        build:
            context: mpich
            args:
                MPICH_VERSION: "${MPICH_VERSION}"
                BASE_DISTRO: "${BASE_DISTRO}"
    openmpi:
        image: pikrog/openmpi:${OPENMPI_VERSION}-${BASE_DISTRO_TAG}
        build:
            context: openmpi
            args:
                OPENMPI_VERSION: "${OPENMPI_VERSION}"
                BASE_DISTRO: "${BASE_DISTRO}"
    mpich-node:
        image: pikrog/mpich-node:${VERSION_TAG}-${BASE_DISTRO_TAG}
        build:
            context: mpi-node
            args:
                MPI_VERSION_TAG: "${MPICH_VERSION}"
                BASE_DISTRO_TAG: "${BASE_DISTRO_TAG}"
                BASE_IMAGE_NAME: "pikrog/mpich"
                DEFAULT_HOST_FILE_ENV: "HYDRA_HOST_FILE"
    openmpi-node:
        image: pikrog/openmpi-node:${VERSION_TAG}-${BASE_DISTRO_TAG}
        build:
            context: mpi-node
            args:
                MPI_VERSION_TAG: ${OPENMPI_VERSION}
                BASE_DISTRO_TAG: ${BASE_DISTRO_TAG}
                BASE_IMAGE_NAME: "pikrog/openmpi"
                DEFAULT_HOST_FILE_ENV: "OMPI_MCA_orte_default_hostfile"
