services:
    worker:
        image: pikrog/openmpi-node:1.0-bullseye
        networks:
          - main-network
        volumes:
          - type: bind
            source: ./workdir/
            target: /home/user/mpi/
    master:
        depends_on:
          - worker
        image: pikrog/openmpi-node:1.0-bullseye
        environment:
            MASTER_HOSTNAME: "master"
            WORKER_HOSTNAME: "worker"
            NODE_MODE: "master"
        networks:
          - main-network
        ports:
          - target: 22
            host_ip: localhost
            published: 22
            protocol: tcp
        volumes:
          - type: bind
            source: ./workdir/
            target: /home/user/mpi/

networks:
    main-network:
