##############################################################
#        MPI Cluster Master Production (custom keys)         #
##############################################################

# Place your SSH public keys in the ./keys subdirectory
# Then build this image

FROM pikrog/mpi-master-ssh-base:0.3
